server:
  port: 8888
spring:
  application:
    name: config-service
  #repo local
  cloud:
    config:
      server:
        git:
          uri: D:\\workspace\\config-mobile
          clone-on-start: true
          default-label: main
application:
  title: config-service
  version: 0.0.1.SNAPSHOOT